//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaAppLOLGG.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seans
    {
        public int Id { get; set; }
        public string Movie { get; set; }
        public string Nachalo { get; set; }
        public string Konec { get; set; }
        public Nullable<int> Zal { get; set; }
    
        public virtual Zali Zali { get; set; }
    }
}
